import argparse
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import instapi

# parse command line arguments
parser = argparse.ArgumentParser(description='Analyze and plot data from API.')
parser.add_argument('-i','--infile', required=True,
    help='Input CSV file generated by API class')
args = parser.parse_args()

matplotlib.style.use('ggplot')
api = instapi.InstAPI('098d66091c6f449ab8e5649403ced1d8')

infile_splitted = args.infile.split('_')
tag = infile_splitted[0]

data = pd.read_csv(args.infile)
data.columns = ['url', 'timestamp','likes']
data = data.drop('url', axis=1)
n = data.likes.count()

data['hour'] = data.timestamp.apply(lambda x: api.timestamp2date(x).hour)
likes_by_hour = data.groupby(data.hour).likes.sum()

newest_post_date = api.timestamp2date(data.head(1).timestamp)
oldest_post_date = api.timestamp2date(data.tail(1).timestamp)

# number of pictures per hour
posts_per_hour = data.groupby(data.hour).likes.count()

# average number of likes by hour
avg_likes_by_hour = likes_by_hour / posts_per_hour

###
# PLOT DATA
###
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(21,9))
fig.subplots_adjust(top=0.9)
supt = '#{} n={} newst={} oldest={}'.format(tag, n, newest_post_date,
    oldest_post_date)
fig.suptitle(supt, fontsize=14, fontweight='bold')

# likes by hour
likes_by_hour.plot(kind='bar', ax=ax1)
ax1.set_xlabel('')
ax1.set_ylabel('Number of likes')
ax1.set_title('Number of Likes by Hour')

# number of pictures per hour
posts_per_hour.plot(kind='bar', ax=ax2)
ax2.set_ylabel('Number of posts')
ax2.set_xlabel('Hour posted (UTC/GMT +2h)')
ax2.set_title("Number of Pictures per Hour")

# average likes
avg_likes_by_hour.plot(kind='bar', ax=ax3)
ax3.set_ylabel('Average number of likes')
ax3.set_xlabel('')
ax3.set_title("Average number of likes by hour")